import Images from "./Images";

export const planets = [
  {
    name: "Mercury",
    nickName: "The Swift Planet",
    color: "orange",
    hasRing: false,
    background: Images.mercury_bg,
    tagline: 'Mercury is the closest planet to the sun, but ice exists on it.',
    lengthOfYear: '88 Earth days',
  },
  {
    name: "Venus",
    nickName: "The Morning star",
    color: "silver",
    hasRing: false,
    background: Images.venus_bg,
    tagline: 'Venus is the hottest planet in the solar system.',
    lengthOfYear: '225 Earth days',
  },
  {
    name: "Earth",
    nickName: "The Blue planet",
    color: "blue",
    hasRing: false,
    background: Images.earth_bg,
    tagline: 'Earth’s atmosphere protects us from meteoroids and radiation from the Sun.',
    lengthOfYear: '365.24 days',
  },
  {
    name: "Mars",
    nickName: "The Red planet",
    color: "red",
    hasRing: false,
    background: Images.mars_bg,
    tagline: 'There have been more missions to Mars than any other planet.',
    lengthOfYear: '1.9 Earth years',
  },
  {
    name: "Jupiter",
    nickName: "The Gaint planet",
    color: "teal",
    hasRing: false,
    background: Images.jupiter_bg,
    tagline: 'Jupiter has more than double the mass of all the other planets combined.',
    lengthOfYear: '11.9 Earth years',
  },
  {
    name: "Saturn",
    nickName: "The Ringed planet",
    color: "yellow",
    hasRing: true,
    background: Images.saturn_bg,
    tagline: 'Saturn has more moons than any other planet in the Solar System.',
    lengthOfYear: '29.5 Earth years',
  },
  {
    name: "Uranus",
    nickName: "The Ice giant",
    color: "green",
    hasRing: false,
    background: Images.uranus_bg,
    tagline: 'Uranus has only been visited by a single spacecraft, Voyager 2.',
    lengthOfYear: '84.0 Earth years',
  },
  {
    name: "Neptune",
    nickName: "The Big blue planet",
    color: "lightblue",
    hasRing: true,
    background: Images.neptune_bg,
    tagline: 'It takes more than 4 hours for light to reach Neptune from the Sun.',
    lengthOfYear: '164.8 Earth years',
  },
];
