export const planets = [
  {
    name: "Mercury",
    color: "orange",
    hasRing: false,
    background: require("../assets/Images/mercury_bg.jpg"),
    tagline: 'Mercury is the closest planet to the sun, but ice exists on it.',
  },
  {
    name: "Venus",
    color: "silver",
    hasRing: false,
    background: require("../assets/Images/venus_bg.jpg"),
    tagline: 'Venus is the hottest planet in the solar system.',
  },
  {
    name: "Earth",
    color: "blue",
    hasRing: false,
    background: require("../assets/Images/earth_bg.jpg"),
    tagline: 'Earth’s atmosphere protects us from meteoroids and radiation from the Sun.',
  },
  {
    name: "Mars",
    color: "red",
    hasRing: false,
    background: require("../assets/Images/mars_bg.jpg"),
    tagline: 'There have been more missions to Mars than any other planet.',
  },
  {
    name: "Jupiter",
    color: "teal",
    hasRing: false,
    background: require("../assets/Images/jupiter_bg.jpg"),
    tagline: 'Jupiter has more than double the mass of all the other planets combined.',
  },
  {
    name: "Saturn",
    color: "yellow",
    hasRing: true,
    background: require("../assets/Images/saturn_bg.jpg"),
    tagline: 'Saturn has more moons than any other planet in the Solar System.',
  },
  {
    name: "Uranus",
    color: "green",
    hasRing: false,
    background: require("../assets/Images/uranus_bg.jpg"),
    tagline: 'Uranus has only been visited by a single spacecraft, Voyager 2.',
  },
  {
    name: "Neptune",
    color: "lightblue",
    hasRing: true,
    background: require("../assets/Images/neptune_bg.jpg"),
    tagline: 'It takes more than 4 hours for light to reach Neptune from the Sun.',
  },
];
